### ISSUE TITLE
Proposal of shared credentials across gridscale tools.

### ISSUE THREAD

**Issue by nvthongswansea** [gridscale/terraform-provider-gridscale#183]
Regarding to #124. I, @bkircher, and the customers really want to have shared-credential feature in all gridscale tools (which are built on top of gridscale public API). The concept is to define a single config file in a common directory, e.g., `$HOME/.config/gridscale/", which will be used by any gridscale tools. This shared config file can also be created by any gs tools (incl. libraries). I would like to propose a schema of this config file as below:
1. It locates at User-level Configuration directory:
  - Linux: `$XDG_CONFIG_HOME/gridscale/config.yml` or `$HOME/.config/gridscale/config.yml`
  - MacOS: `$HOME/Library/Application Support/gridscale/config.yml`
  - Windows: `%APPDATA%\gridscale\config.yml` or `C:\Users\%USER%\AppData\Roaming\gridscale\config.yml`

2. It is a yaml file with following scheme:
```yml
accounts:
- name: default
  userId: xx-xxx-xxx-xxx-xxx
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  url: https://api.gridscale.io
- name: second-project
  userId: xx-xxx-xxx-xxx-xxx
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  url: https://api.gridscale.io
```
Please feel free to comment.

**Comment by bkircher** [comment]
Hey thanks for opening this!

All looks good here. I would name the file `projects.yaml` rather than `config.yml` and also the top-level list, I would name `projects:` rather than `accounts:`. This would be more consistent with what is in the panel and in the UI. "Account" really is a new word.

**Comment by nvthongswansea** [comment]
@bkircher that sounds great.

**Comment by bkircher** [comment]
OK cool. You think we should wait a couple more days to give other's a chance to answer?

...before we start implementing that?

I could do the changes in gscloud and the Python library.

**Comment by nvthongswansea** [comment]
@bkircher sure, I've already opened issues in those repos. Just wait!

**Comment by itakouna** [comment]
I'm with changing the `accounts` to `projects`, but I would rather keep `gridscale/config.yml`

**Comment by bkircher** [comment]
OK, to sum up, path will be `gridscale/config.yaml` in the usual platform specific locations and contents will be like

```
projects:
- name: default
  userId: xyz
  token: xyz
  url: https://api.gridscale.io
- name: somthing-else
  userId: xyz
  token: xyz
  url: https://api.gridscale.io
  ```
